import { StyleSheet } from 'react-native';
import { Constants } from '../constants/Constants';

export const cartStyles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        backgroundColor: 'white',
        width: '100%',
        height: '100%',
        paddingVertical: 30,
        backgroundColor: '#FAFAFA'
    },
    header: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        marginBottom: 40,
        backgroundColor: '#FAFAFA'
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfOrange,
        paddingHorizontal: 20,
    },
    headerTitleBig: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfOrange,
        paddingHorizontal: 20,
    },
    headerTitleEmpty: {
        fontSize: 25,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
        paddingHorizontal: 20,
        textAlign: 'center',
        maxWidth: 400,
    },
    
    productCard: {
        width: '100%',
        height: 60,
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        borderColor: '#000',
        justifyContent: 'space-between',
        backgroundColor: '#FAFAFA'
    },
    productName: {
        fontSize: 11,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
    },
    productPrice: {
        fontSize: 13,
        fontWeight: 'normal',
        color: Constants.COLORS.cdfBlue,
        width: 80,
        textAlign: 'right',
    },
    quantityCircle: {
        width: 35,
        height: 35,
        borderRadius: 50,
        backgroundColor: 'white',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: Constants.COLORS.cdfBlue,
    },
    quantityBlock: {
        width: '20%',
        height: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 30,
        backgroundColor: '#FAFAFA'
    },
    contentBlock: {
        width: '80%',
        height: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingRight: 20,
        backgroundColor: '#FAFAFA'
    },
    subtotalBtn: {
        position: 'absolute',
        bottom: 20,
        right: 0,
        left: 0,
        marginHorizontal: 20,
        height: 60,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfBlue,
        borderRadius: 50,
    },
    subtotalBtnText: {
        fontWeight: 'bold',
        color: 'white',
    },
    footer: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 20,
        backgroundColor: Constants.COLORS.cdfOrange,
        position: 'absolute',
        bottom: 0,
        gap: 20
    },
    footerEdit: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfOrange,
        position: 'absolute',
        bottom: 0,
        gap: 20
    },
    footerEditSection: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'white',
        gap: 20,
        paddingVertical: 20,
        paddingHorizontal: 20,
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 3,
        shadowOffset: { width: 10, height: 20 },
    },
    footerContent: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfOrange,
    },
    footerContentEdit: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: 'white',
        gap: 20,
    },
    footerContentEditBottom: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfOrange,
        paddingBottom: 20,
        paddingHorizontal: 20,
    },
    footerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
    },
    footerTitleEdit: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
    },
    footerTitleEditSmall: {
        fontSize: 15,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
    },
    footerPrice: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
    },
    footerPriceEdit: {
        fontSize: 20,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
    },
    footerButton: {
        height: 60,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfBlue,
        borderRadius: 50,
        borderWidth: 0,
        width: '100%',

        borderWidth: 0,
        shadowOffset: { width: 10, height: 10 },
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 3,
    },

    updateButton: {
        height: 60,
        width: 200,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfBlue,
        borderRadius: 50,
        borderWidth: 0,
        borderWidth: 0,
        shadowOffset: { width: 10, height: 10 },
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 3,
    },

    footerButtonText: {
        fontWeight: 'bold',
        color: 'white',
    },
    rightSwipeAction: {
        paddingLeft: 10,
        borderTopLeftRadius: 20,
        borderBottomLeftRadius: 20,
        height: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfOrange,
    },
    rightSwipeActionIcon: {
        color: 'white',
    },
    leftSwipeAction: {
        paddingLeft: 20,
        paddingRight: 30,
        borderTopRightRadius: 20,
        borderBottomRightRadius: 20,
        height: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfBlue,
    },
    stripePaymentButton: {
        width: '100%',
        height: 60,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfBlue,
        borderRadius: 50,
        borderWidth: 0,
        borderWidth: 0,
        shadowOffset: { width: 10, height: 10 },
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 3,
    },
});

export const paymentStyles = StyleSheet.create({
    bottomSheet: {
        display: 'flex',
        flexDirection: 'column',
    },
    paymentContainer: {
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 10,
    },
    paymentTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfOrange,
        marginBottom: 20,
    },
    paymentHeader: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    paymentCloseText: {
        fontSize: 15,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
    },
    paymentBody: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        paddingHorizontal: 20,
    },
    informationContainer: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        marginBottom: 20,
        borderWidth: 2,
        borderColor: 'black',
    },
    sectionHeader: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 25,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
    },
    sectionSecondText: {
        fontSize: 15,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfOrange,
        textDecorationLine: 'underline',
    },
    informationBody: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    informationRow: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 10,
        gap: 20,
    },
    informationLabel: {
        fontSize: 15,
        fontWeight: 'normal',
        color: Constants.COLORS.cdfBlue,
    },
    informationValue: {
        fontSize: 15,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
        flexWrap: 'wrap',
        maxWidth: '70%'
    },
    addressItem: {
        marginBottom: 10,
        width: '100%',
        paddingVertical: 5,
        display: 'flex',
        flexDirection: 'row',
    },
    recapContainer: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    recapBody: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    notesInput: {
        width: '100%',
        borderWidth: 2,
        marginBottom: 20,
    },
    paymentTypeContainer: {
        width: '100%',

        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    paymentTypeCard: {
        width: 90,
        height: 90,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
    },
    paymentTypeImage: {
        width: 40,
        height: 40,   
    },
    stripeButton: {
        width: '100%',
        height: 60,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#635bff',
        shadowOffset: { width: 10, height: 10 },
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 3,
        borderRadius: 50,
        flexDirection: 'row',
        gap: 10,
    }
});