import { StyleSheet } from 'react-native';
import { Constants } from '../constants/Constants';

export const productsStyles = StyleSheet.create({
    container: {
        flex: 1,
        flexGrow: 1,
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        backgroundColor: 'white',
        width: '100%',
        height: '100%',
        paddingVertical: 20,
    },
    header: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',

    },
    searchBlock: {
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 20,
        paddingBottom: 20,
        paddingHorizontal: 10,
    },
    searchBarContainer: {
        width: '100%',
        height: 40,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-between',
        alignItems: 'center',
        backgroundColor: '#F0F0F0',
        gap: 20
    },
    searchBarText: {
        fontSize: 18,
        fontWeight: 'normal',
        color: '#717171',
    },
    searchBarInput: {
        flex: 1,
        width: '100%',
        height: '100%',
        fontSize: 18,
        fontWeight: 'normal',
        color: '#717171',
        backgroundColor: '#F0F0F0',
        borderWidth: 0,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfOrange,
        paddingHorizontal: 20,
        textTransform: 'uppercase',
        paddingBottom: 20,  
    },
    searchIcon: {
        width: 30,
        height: 30,

    },
    productCard: {
        width: '100%',
        height: 140,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderColor: Constants.COLORS.cdfBlue,
    },
    productCardSearch: {
        width: '100%',
        height: 140,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    productCardOrder: {
        width: '100%',
        height: 100,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    imageBlock: {
        width: 100,
        height: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 15,
        paddingVertical: 30,
    },
    imageBlockOrder: {
        width: 100,
        height: 80,
        height: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        paddingRight: 25,
        paddingVertical: 15,
    },
    contentBlock: {
        width: '70%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'flex-start',
        paddingRight: 20,
    },
    contentBlockOrder: {
        flex: 1,
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        paddingRight: 20,
        paddingVertical: 15,
    },
    productName: {
        fontSize: 14,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
    },
    productDescription: {
        fontSize: 14,
        color: Constants.COLORS.cdfBlue,
        textTransform: 'lowercase',
    },
    productPrice: {
        fontSize: 15,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
    },
    productQtPrice: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        marginTop: 20,
    },
    subcategories: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        marginTop: 20,
    },
    subcategory: {
        width: 100,
        height: 40,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomWidth: 3,
        borderBottomColor: Constants.COLORS.cdfBlue,
    },
    subcategoryActive: {
        width:100,
        height: 40,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomWidth: 3,
        borderBottomColor: Constants.COLORS.cdfOrange,
    },
    subcategoryName: {
        fontSize: 14,
        fontWeight: 'bold',
        color: Constants.COLORS.cdfBlue,
        textTransform: 'uppercase',
    },
    subcategoryNameActive: {
        fontSize: 14,
        fontWeight: 'bold',
        width: '100%',
        textAlign: 'center',
        lineHeight: 40,
        textTransform: 'uppercase',

    },
    subtotalBtn: {
        position: 'absolute',
        bottom: 20,
        right: 0,
        left: 0,
        marginHorizontal: 20,
        height: 60,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Constants.COLORS.cdfBlue,
        borderRadius: 50,
        borderWidth: 0,

        shadowOffset: { width: 10, height: 10 },
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 3,
    },
    subtotalBtnText: {
        fontWeight: 'bold',
        color: 'white',
        fontSize: 12
    },
    loadingContainer: {
        width: '100%',
        height: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 30
    }
});