import { StyleSheet } from 'react-native';
import { Constants } from '../constants/Constants';

export const welcomeStyles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 30,
        backgroundColor: 'white',
        paddingHorizontal: 50,
        height: '100%',
        width: '100%',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 10,
        color: Constants.COLORS.cdfBlue,
        marginTop: 30,
    },
    subtitle: {
        fontSize: 19,
        marginBottom: 30,
        marginTop: 20,
        fontWeight: 'normal',
        color: Constants.COLORS.cdfBlue,
        textAlign: 'center',
    },
    buttonsContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        gap: 20,
    },
    authButton: {
        backgroundColor: Constants.COLORS.cdfBlue,
        flex: 1,
        height: 50,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        borderRadius: 50,
        borderWidth: 0,
    },
    authButtonWide: {
        backgroundColor: Constants.COLORS.cdfBlue,
        height: 60,
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        borderRadius: 20,
        borderWidth: 0,
        marginTop: 40,
    },
    authButtonWhite: {
        backgroundColor: '#fff',
        flex: 1,
        height: 50,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        borderRadius: 50,
        borderWidth: 2,
        borderColor: Constants.COLORS.cdfBlue,
    },
    authButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 18,
    },
    authButtonTextWhite: {
        color: Constants.COLORS.cdfBlue,
        fontWeight: 'bold',
        fontSize: 18,
    },
    input: {
        marginTop: 20,
        width: '100%',
        backgroundColor: '#fff',
        borderWidth: 0,

        shadowColor: 'black',
        shadowOpacity: 0.05,
        shadowOffset: { width: 10, height: 10 },
        elevation: 2,
        
        borderRadius: 20,
    },
    link: {
        color: Constants.COLORS.cdfOrange,
        fontWeight: 'bold',
        fontSize: 18,
        textAlign: 'center',
    },
    socialContainer: {
        display: 'flex',
        flexDirection: 'column',    
        width: '100%',
        gap: 20,
    },
    orText: {
        color: Constants.COLORS.cdfBlue,
        fontWeight: 'bold',
        fontSize: 18,
        textAlign: 'center',
        marginBottom: 20,
    },
    existingAccountText: {
        color: Constants.COLORS.cdfBlue,
        fontWeight: '600',
        fontSize: 18,
        textAlign: 'center',
        marginBottom: 10,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    forgotPasswordText: {
        color: Constants.COLORS.cdfBlue,
        fontWeight: '600',
        fontSize: 18,
        textAlign: 'center',
        marginBottom: 40,
        textDecorationLine: 'underline',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },  
    existingAccountLinkText: {
        color: Constants.COLORS.cdfOrange,
        fontWeight: 'bold',
        fontSize: 18,
        textAlign: 'center',
        marginBottom: 20,
        textDecorationLine: 'underline',
    },
});